//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForm.LINQ
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRecord
    {
        public int rId { get; set; }
        public int account_id { get; set; }
        public System.DateTime rdate { get; set; }
        public byte[] rPhoto { get; set; }
        public string rTitle { get; set; }
        public string rContent { get; set; }
    }
}
